# Generated by Django 4.2.9 on 2024-10-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='static/assets/avatars/ladybug.png', max_length=255, upload_to=''),
        ),
    ]
