# Generated by Django 4.2.9 on 2024-10-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_uploaded_avatar_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uploaded_avatar',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='assets/avatars/ladybug.png', max_length=255, upload_to='avatars/'),
        ),
    ]
