# Generated by Django 4.2.9 on 2024-10-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_customuser_intra_42_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='accounts_customuser',
        ),
    ]
