services:
  database:
    restart: always
    container_name: database
    build:
      dockerfile: Dockerfile
      context: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - transcendence-network
    env_file:
      - .env

  redis:  # Nouveau service Redis
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - transcendence-network
    volumes:
      - redis_data:/data  # Pour sauvegarder les données Redis

  backend:
    restart: always
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/app
      - ./backend/certs:/app/certs
      - ./backend/templates:/app/templates
      - media:/app/media
    ports:            # Remplacer 'expose' par 'ports'
      - "8443:8443"   # Format "port_hôte:port_conteneur"
    depends_on:
      - database
      - redis
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - .env
    networks:
      - transcendence-network

  frontend:
    restart: always
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - transcendence-network
    ports:
      - "4430:443"
    volumes:
      - media:/app/media

  route-tester:
    build:
      context: ./tests
      dockerfile: Dockerfile.test
    container_name: route-tester
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-network
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
      - ./backend/certs:/app/certs  # Ajoutez l'accès aux certificats
    environment:
      - FRONTEND_URL=https://frontend:443
      - BACKEND_URL=https://backend:8443
      - SSL_CERT_FILE=/app/certs/gunicorn.crt


volumes:
  postgres_data:
    name: postgre_data
  media:
    name: media_volume
  redis_data:  # Nouveau volume pour Redis
    name: redis_data

networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge
